apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service-deployment
  labels:
    app: demo-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
      - name: demo-service
        image: dev/demo-service:v2 # 注意这里的 image 版本变成了 v2
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: demo-service-config # 注入上述创建的 ConfigMap 中的所有 KV 作为环境变量
