apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080 # 指定外部访问的端口，范围必须在 30000-32767
  selector:
    app: demo-service
